id = "ocean-green"
name = "Ocean Green"
schema_version = 1
version = "0.0.1"
authors = ["Trace Panic <tracepanic.com>"]
description = "And now I have been become green"
repository = "https://github.com/tracepanic/zed-ocean-green"
